# Generated by Django 5.0.7 on 2024-07-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
